version: 1.0.{build}
os: Visual Studio 2017

cache:
  - C:\Users\appveyor\.m2 -> **\pom.xml

install:
  - ps: [string]$mavenVersion = "3.5.0"
  - ps: choco install maven --limit-output --version $mavenVersion
  - ps: $env:Path += ;C:\bin\apache-maven-$mavenVersion\bin
  - mvn --version
  - java -version

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  MSBUILD_PATH: C:\PROGRA~2\MSBuild\14.0\Bin\MSBuild.exe

build_script:
  - mvn clean install "--batch-mode"

test: off

notifications:
- provider: HipChat
  room: 409390
  auth_token:
    secure: RW8+2GpOWo3PcoM3ehoI+mbfUr7h508RtTDyszpR6/E=
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
